INSERT INTO burgers(burName, burPhoto) VALUES("50/50 burger", "/assets/img/505.svg");
INSERT INTO burgers(burName, burPhoto) VALUES("Angus burger", "/assets/img/ANGUS.svg");
INSERT INTO burgers(burName, burPhoto) VALUES("Kiwiburger", "/assets/img/kiwi.svg");
INSERT INTO burgers(burName, burPhoto) VALUES("Bacon cheeseburger", "/assets/img/bacon.svg");
INSERT INTO burgers(burName, burPhoto) VALUES("Barbecue burger", "/assets/img/bbq.svg");
INSERT INTO burgers(burName, burPhoto) VALUES("Bøfsandwich", "/assets/img/bBøfsandwich.svg");
INSERT INTO burgers(burName, burPhoto) VALUES("Butter burger", "/assets/img/butter.svg");
INSERT INTO burgers(burName, burPhoto) VALUES("Buffalo burger", "/assets/img/buffalo.svg");
INSERT INTO burgers(burName, burPhoto) VALUES("California burger", "/assets/img/california.svg");
INSERT INTO burgers(burName, burPhoto) VALUES("Carolina burger", "/assets/img/carolina.svg");