USE burgers_db;
INSERT INTO burgers(burName, burPhoto) VALUES("50/50 burger", "/assets/img/505.jpg");
INSERT INTO burgers(burName, burPhoto) VALUES("Angus burger", "/assets/img/ANGUS.jpg");
INSERT INTO burgers(burName, burPhoto) VALUES("Kiwiburger", "/assets/img/kiwi.jpg");
INSERT INTO burgers(burName, burPhoto) VALUES("Bacon cheeseburger", "/assets/img/bacon.jpg");
INSERT INTO burgers(burName, burPhoto) VALUES("Barbecue burger", "/assets/img/bbq.jpg");
INSERT INTO burgers(burName, burPhoto) VALUES("Bøfsandwich", "/assets/img/bBøfsandwich.jpg");
INSERT INTO burgers(burName, burPhoto) VALUES("Butter burger", "/assets/img/butter.jpg");
INSERT INTO burgers(burName, burPhoto) VALUES("Buffalo burger", "/assets/img/buffalo.jpg");
INSERT INTO burgers(burName, burPhoto) VALUES("California burger", "/assets/img/california.jpg");
INSERT INTO burgers(burName, burPhoto) VALUES("Carolina burger", "/assets/img/carolina.jpg");
